import * as RB from 'react-bootstrap'
import { useState, useEffect } from 'react'
import { Cookies } from 'react-cookie'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export function login(){
    const cookies=new Cookies()

    // const [userdata, setdata]=useState({
    //     username:'',
    //     jwt:''
    // })
    // const [username, setuser]=useState()
    // const [jwt, setjwt]=useState()
    // if(cookies.get('user') && cookies.get('user').jwt!='') {
    //     // console.log("cookies",cookies.get('user'))
    //     // setuser(cookies.get('user').username)
    //     // setjwt(cookies.get('user').jwt)
    //     // console.log(userdata)
    // }
    
    return(
        <>
        {cookies.get('user')? 
        ('my name is ' + cookies.get('user').username + 'and currently i have jwt: '+ cookies.get('user').jwt):
        (<Loginform />)}
        {/* {userdata.username} */}
        {/* <Loginform /> */}
        </>
    )
}

const Loginform=()=>{
    const cookies=new Cookies()
    const handleSubmit=e=>{
        e.preventDefault()
        fetch(`http://127.0.0.1:1337/api/auth/local`,{
                method:"POST",
                headers:{ "Content-Type":"application/json" },
                body:JSON.stringify({identifier:e.target[0].value,password:e.target[1].value})
            })
            .then(async res => {
                if (res.status == 200) {
                    let d = await res.json()
                    cookies.set("user",{username:d.user.username, jwt:d.jwt})
                }
            })
            .catch(e => {
                if (e instanceof Error) console.log("fetch error",e.message)
            })
    }
    
    return(
        <div className={styles.container}>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by simple pokedex" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    rel="stylesheet"
                    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
                    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
                    crossOrigin="anonymous"
                />
            </Head>
            <main className={styles.main}>
                <RB.Form onSubmit={handleSubmit} onReset={null}>
                    <RB.Row>
                        <RB.Form.Group className="mb-3">
                            <RB.Form.Label>username</RB.Form.Label>
                            <RB.Form.Control placeholder='Enter username' name='username' required/>
                        </RB.Form.Group>
                        <RB.Form.Group className="mb-3">
                            <RB.Form.Label>password</RB.Form.Label>
                            <RB.Form.Control placeholder='Enter password' name='password' required/>
                        </RB.Form.Group>
                    </RB.Row>
                    <RB.ButtonToolbar aria-label="Toolbar btngroup">
                        <RB.ButtonGroup className="me-2">
                            <RB.Button variant="primary" type="submit" name="submit">Submit</RB.Button>
                        </RB.ButtonGroup >
                        <RB.ButtonGroup className="me-2">
                            <RB.Button variant="primary" type="reset" name="reset">Reset</RB.Button>
                        </RB.ButtonGroup >
                    </RB.ButtonToolbar>
                </RB.Form>
                    
            </main> 
        </div>
    )
}

