import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Simple PokeDex</title>
        <meta name="description" content="Generated by simple pokedex" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
                  {/*Welcome to <a href="https://nextjs.org">Next.js!</a>*/}
                  Welcome to my <a href="/">Simple PokeDex!</a>
        </h1>

        <p className={styles.description}>
                  Currently my PokeDex {props.data?"have "+props.data:"didn't have " } pokemon!
        </p>

        <div className={styles.grid}>
          {/*<a href="https://nextjs.org/docs" className={styles.card}>*/}
          {/*  <h2>Documentation &rarr;</h2>*/}
          {/*  <p>Find in-depth information about Next.js features and API.</p>*/}
          {/*</a>*/}
                  <a href="http://localhost:3000/list/pokemon" className={styles.card}>
            <h2>Click me &rarr;</h2>
            <p>Find my pokemon list</p>
            <Image alt="" src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png" width={100} height={100}></Image>
            <Image alt="" src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png" width={100} height={100}></Image>
          </a>

          {/*<a href="https://nextjs.org/learn" className={styles.card}>*/}
          {/*  <h2>Learn &rarr;</h2>*/}
          {/*  <p>Learn about Next.js in an interactive course with quizzes!</p>*/}
          {/*</a>*/}

          {/*<a*/}
          {/*  href="https://github.com/vercel/next.js/tree/canary/examples"*/}
          {/*  className={styles.card}*/}
          {/*>*/}
          {/*  <h2>Examples &rarr;</h2>*/}
          {/*  <p>Discover and deploy boilerplate example Next.js projects.</p>*/}
          {/*</a>*/}

          {/*<a*/}
          {/*  href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
          {/*  className={styles.card}*/}
          {/*>*/}
          {/*  <h2>Deploy &rarr;</h2>*/}
          {/*  <p>*/}
          {/*    Instantly deploy your Next.js site to a public URL with Vercel.*/}
          {/*  </p>*/}
          {/*</a>*/}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
    const res = await fetch('http://127.0.0.1:1337/api/pokemoncount').catch((err) => console.log(err));
    const d = await res.json()
    var data = null
    try{
      data=d.data.attributes.count
    }catch(e){}
    return {
        props: {
            data
        }
    }
}
